import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, } from "react-icons/ai";
import profilephoto from "../public/profile-photo.jpg"
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <>
     <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Will Dunwoody Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white p-10 md:px-20 lg:px-40 xl:px-80 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="mb-12 flex justify-between">
            <h1 className="text-lg font-burtons">Will Dunwoody</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-md"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="https://www.linkedin.com/in/willdunwoody/">Resume</a>
              </li>
            </ul>
          </nav>

          <div className="text-center">
            <h2 className="text-3xl py-2 text-teal-400 font-medium">Will Dunwoody</h2>
            <h3 className="text-xl py-2 md:text-3xl">Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugit sit repellat error, eaque consectetur debitis animi ducimus, quae maxime eligendi iste voluptas itaque, adipisci magni aliquam repellendus explicabo sint culpa.</p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/willdunwoody/"><AiFillLinkedin /></a>
            <a href="http://github.com/WillDunwoody"><AiFillGithub /></a>
            <a href="https://twitter.com/WDunwood/"><AiFillTwitterCircle /></a>
          </div>

          <div className="relative mx-auto w-60 my-10">
            <Image src={profilephoto} alt={"profile"} className="rounded-full"/>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus consectetur debitis consequuntur sequi necessitatibus libero, explicabo, nam eligendi accusamus quam voluptate quae nemo id temporibus eveniet aspernatur aut voluptas neque.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beauftiful Designs</h3>
              <p className="py-2">
                Create beautifully designed websites
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beauftiful Designs</h3>
              <p className="py-2">
                Create beautifully designed websites
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Beauftiful Designs</h3>
              <p className="py-2">
                Create beautifully designed websites
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus consectetur debitis consequuntur sequi necessitatibus libero, explicabo, nam eligendi accusamus quam voluptate quae nemo id temporibus eveniet aspernatur aut voluptas neque.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1"><Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"><Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"><Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"><Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"><Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"><Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" /></div>
          </div>
        </section>
      </main>
      </div>
    </>
  )
}
